
find_program (CMAKE_MAKE_PROGRAM make)

set (CMAKE_SYSTEM_NAME Generic)
set (CMAKE_SYSTEM_PROCESSOR arm-none-eabi)
set (CMAKE_SYSROOT ${DEVKITPRO_ROOT}/${CMAKE_SYSTEM_NAME})

set (CMAKE_FIND_ROOT_PATH ${DEVKITPRO_ROOT})

set (CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set (CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set (CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set (CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)


set (CMAKE_OBJCOPY ${DEVKITPRO_ROOT}/bin/${CMAKE_SYSTEM_PROCESSOR}-objcopy)
set (CMAKE_LINKER ${DEVKITPRO_ROOT}/bin/${CMAKE_SYSTEM_PROCESSOR}-ld)
set (CMAKE_C_COMPILER ${DEVKITPRO_ROOT}/bin/${CMAKE_SYSTEM_PROCESSOR}-gcc)
set (CMAKE_CXX_COMPILER ${DEVKITPRO_ROOT}/bin/${CMAKE_SYSTEM_PROCESSOR}-g++)
set (CMAKE_STRIP ${DEVKITPRO_ROOT}/bin/${CMAKE_SYSTEM_PROCESSOR}-strip)

set (GBAFIX ${DEVKITPRO_ROOT}/bin/gbafix)

set (ARCH "-mthumb-interwork -mthumb")
set (SPECS -specs=gba.specs)

set (CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${ARCH} -fno-strict-aliasing")
set (CMAKE_GBA_LINKER_FLAGS "${ARCH} ${SPECS} -Wl,-Map=rom.map")
